version: "3"
services:
  redis-server:
    image: "redis:alpine"
  tornado-app:
    restart: always
    build: .
    ports:
      - 8000:8000
    env_file:
      - ".env"
    environment:
      - PORT=8000
      - REDIS_PORT=6379
      - ENVIRONMENT=PROD
    depends_on:
      - redis-server