version: "3"
services:
  redis-server:
    image: "redis:alpine"
    command: --port 6380
  tornado-app:
    restart: always
    build: .
    ports:
      - 9000:9000
    env_file:
      - ".env"
    environment:
      - PORT=9000
      - REDIS_PORT=6380
      - ENVIRONMENT=DEV
    depends_on:
      - redis-server